export enum Currency {
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  CAD = 'CAD',
  CNY = 'CNY',
  KRW = 'KRW',
  JPY = 'JPY',
  RUB = 'RUB',
  AUD = 'AUD',
  NZD = 'NZD',
  CHF = 'CHF',
  SGD = 'SGD',
  INR = 'INR',
  BRL = 'BRL',
  ETH = 'ETH',
  BTC = 'BTC',
  HKD = 'HKD',
  SEK = 'SEK',
  NOK = 'NOK',
  MXN = 'MXN',
  TRY = 'TRY',
}
